DROP TABLE IF EXISTS POSITION CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS ACCOUNT_POSITION CASCADE;
DROP TABLE IF EXISTS ORDERS CASCADE;
DROP TABLE IF EXISTS TRANSACTION CASCADE;
DROP TABLE IF EXISTS TRANSACTION_ORDER CASCADE;
CREATE TABLE POSITION(
POSITION_ID INT PRIMARY KEY,
SYMBOL_NAME  VARCHAR(256),
AMOUNT       DOUBLE PRECISION
);
CREATE TABLE ACCOUNT(
ACCOUNT_NUMBER  VARCHAR(512),
BALANCE   VARCHAR(512),
POSITION_COUNT  INT
);
CREATE TABLE ACCOUNT_POSITION(
  ACCOUNT_NUMBER VARCHAR(512),
  POSITION_ID   INT
);
CREATE TABLE ORDERS(
   ORDER_ID INT,
  SYMBOL_NAME VARCHAR(256),
  AMOUNT   DOUBLE PRECISION,
  PRICE_LIMIT DOUBLE PRECISION,
  EXECUTED_AMOUNT DOUBLE PRECISION,
  CANCELED_AMOUNT DOUBLE PRECISION,
  LAST_UPDATE   VARCHAR(256)
);
CREATE TABLE TRANSACTION( 
  TRANSACTION_ID INT,
  ACCOUNT_ID VARCHAR(512),
  TRANSACTION_STATUS INT);
CREATE TABLE TRANSACTION_ORDER(
  TRANSACTION_ID INT,
  ORDER_ID    INT);







